import Foundation
import Testing

@testable import TrackEvolutionKit

/// The port of `test/unit/live-timing.test.js`, plus the cross-language pin.
struct LiveTimingTests {
    let lat0 = 36.56
    let lon0 = -79.2
    var kx: Double { 111320 * cos(lat0 * .pi / 180) }
    let ky = 110540.0
    let r = 200.0

    /// Same synthetic circle as the JS unit tests: 5 Hz, one speed per lap.
    func circleFixes(_ lapSpeeds: [Double], hz: Int = 5) -> [Recording.Fix] {
        var fixes: [Recording.Fix] = []
        var t = 0.0
        var a = 0.0
        let dt = 1.0 / Double(hz)
        for v in lapSpeeds {
            let lapS = 2 * .pi * r / v
            let n = Int((lapS * Double(hz)).rounded())
            for _ in 0..<n {
                fixes.append(Recording.Fix(
                    t: JSMath.round(t, 100),
                    lat: lat0 + r * sin(a) / ky,
                    lon: lon0 + r * cos(a) / kx,
                    v: v,
                    acc: 5
                ))
                t += dt
                a += v * dt / r
            }
        }
        return fixes
    }

    var lap25Ms: Int { JSMath.roundToInt(2 * .pi * r / 25 * 1000)! }

    // ---- the cross-language contract ---------------------------------------

    /// `contracts/logic/live-timing.json` is generated by running the *web*
    /// implementation — assert against the reference, never the Android port.
    @Test func matchesTheJavaScriptImplementationOnASharedFixture() throws {
        let url = RepoRoot.path("contracts/logic/live-timing.json")
        let fixture = try JSONDecoder().decode(LiveTimingFixture.self, from: try Data(contentsOf: url))

        var lt = LiveTiming()
        #expect(fixture.input.fixes.count == fixture.expected.deltaAfterEachFix.count)
        for (i, tuple) in fixture.input.fixes.enumerated() {
            lt.addTimingFix(Recording.Fix(t: tuple[0]!, lat: tuple[1]!, lon: tuple[2]!, v: tuple[3], acc: tuple[4]))
            let want = fixture.expected.deltaAfterEachFix[i]
            switch (want, lt.deltaS) {
            case (nil, nil):
                break
            case let (.some(w), .some(got)):
                #expect(abs(got - w) < 1e-9, "fix \(i): delta \(got) != \(w)")
            default:
                Issue.record("fix \(i): delta \(String(describing: lt.deltaS)) != \(String(describing: want))")
            }
        }

        #expect(lt.lapCount == fixture.expected.lapCount)
        #expect(lt.lastLapMs == fixture.expected.lastLapMs)
        #expect(lt.bestLapMs == fixture.expected.bestLapMs)

        let gate = try #require(lt.gate)
        let wantGate = fixture.expected.gate
        #expect(abs(gate.hx - wantGate.hx) < 1e-9)
        #expect(abs(gate.hy - wantGate.hy) < 1e-9)
        #expect(abs(gate.x1 - wantGate.x1) < 1e-9)
        #expect(abs(gate.y1 - wantGate.y1) < 1e-9)
        #expect(abs(gate.x2 - wantGate.x2) < 1e-9)
        #expect(abs(gate.y2 - wantGate.y2) < 1e-9)

        let display = lt.display(nowS: fixture.input.fixes.last![0]!)
        #expect(display.lapCount == fixture.expected.finalDisplay.lapCount)
        #expect(abs(display.currentLapS! - fixture.expected.finalDisplay.currentLapS!) < 1e-9)
    }

    // ---- ported JS unit tests -----------------------------------------------

    @Test func staysDisarmedBelowTrackPace() {
        var lt = LiveTiming()
        for f in circleFixes([5]).prefix(100) { lt.addTimingFix(f) }
        #expect(lt.gate == nil)
        #expect(lt.display(nowS: 20).currentLapS == nil)
    }

    @Test func armsAtTrackPaceAndTimesLapsAtTheCirclePeriod() {
        let lt = LiveTiming.fromFixes(circleFixes([25, 25, 25, 25]))
        #expect(lt.gate != nil)
        #expect(lt.lapCount == 3)
        #expect(abs(lt.lastLapMs! - lap25Ms) < 150)
        #expect(abs(lt.bestLapMs! - lap25Ms) < 150)
    }

    @Test func showsAGrowingPositiveDeltaOnASlowerLap() {
        let lt = LiveTiming.fromFixes(circleFixes([25, 25, 20]))
        #expect(lt.deltaS! > 8)
    }

    @Test func promotesAFasterLapToTheReference() {
        let lt = LiveTiming.fromFixes(circleFixes([25, 30, 30]))
        let lap30 = JSMath.roundToInt(2 * .pi * r / 30 * 1000)!
        #expect(abs(lt.bestLapMs! - lap30) < 150)
        #expect(lt.bestLapMs! < lap25Ms)
    }

    @Test func negativeDeltaWhenRunningAheadOfTheBestLap() {
        let fixes = circleFixes([25, 30])
        var lt = LiveTiming()
        for f in fixes.prefix(Int(Double(fixes.count) * 0.85)) { lt.addTimingFix(f) }
        #expect(lt.lapCount == 1)
        #expect(lt.deltaS! < -1)
    }

    @Test func armingNeedsARealHeadingNotAGpsTeleportAtZeroSpeed() {
        var lt = LiveTiming()
        lt.addTimingFix(Recording.Fix(t: 0, lat: lat0, lon: lon0, v: LiveTiming.ARM_MPS + 1, acc: 5))
        lt.addTimingFix(Recording.Fix(t: 1, lat: lat0, lon: lon0 + 0.5 / kx, v: LiveTiming.ARM_MPS + 1, acc: 5))
        #expect(lt.gate == nil)
    }
}

/// `contracts/logic/live-timing.json` — reference output captured from
/// `public/js/record/live-timing.js`. The wire names are the JS ones on
/// purpose: this decodes the reference, not our models.
struct LiveTimingFixture: Decodable {
    struct Input: Decodable {
        /// `[tRelS, lat, lon, v|null, acc|null]` tuples.
        var fixes: [[Double?]]
    }

    struct Gate: Decodable {
        var hx: Double
        var hy: Double
        var x1: Double
        var y1: Double
        var x2: Double
        var y2: Double
    }

    struct Display: Decodable {
        var lapCount: Int
        var currentLapS: Double?
        var lastLapMs: Int?
        var bestLapMs: Int?
        var deltaS: Double?
    }

    struct Expected: Decodable {
        var gate: Gate
        var lapCount: Int
        var lastLapMs: Int
        var bestLapMs: Int
        var deltaAfterEachFix: [Double?]
        var finalDisplay: Display
    }

    var input: Input
    var expected: Expected
}
