import { Hono } from "hono";
import type { AppContext } from "../types";

// The seeded car catalog (#221): one row per *generation* of the cars a track
// day actually sees, carrying the two spec-sheet numbers the balance read-out
// needs (wheelbase, steering ratio) and where each number came from. It backs
// the vehicle form's picker the way track_catalog backs the event form's track
// suggestions: a pick pre-fills `vehicles.wheelbase_mm` / `steering_ratio` and
// records `vehicles.catalog_id` as identity, not ownership — the user's own
// values stay editable and the catalog is never consulted again for that row.
//
// Rows come from migrations generated by seed/cars/generate.mjs (Wikidata for
// wheelbases, a hand-curated, cited file for steering ratios); a generation the
// catalog lacks is typed by hand. The whole table is small enough to ship in
// one response, which is what lets the picker work offline from the cache.

export const carCatalog = new Hono<AppContext>();

export type CatalogCar = {
  id: number;
  make: string;
  model: string;
  generation: string | null;
  year_from: number;
  year_to: number | null;
  wheelbase_mm: number;
  steering_ratio: number | null;
  source: string;
};

export const CATALOG_CAR_COLUMNS =
  "id, make, model, generation, year_from, year_to, wheelbase_mm, steering_ratio, source";

carCatalog.get("/car-catalog", async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT ${CATALOG_CAR_COLUMNS} FROM car_catalog
     ORDER BY make COLLATE NOCASE, model COLLATE NOCASE, year_from, generation COLLATE NOCASE`
  ).all<CatalogCar>();
  return c.json(rows.results);
});
