// Generated by apps/ios/Tools/generate-tokens.mjs from public/style.css.
// Do not edit — change the stylesheet's tokens and re-run the generator.

import SwiftUI

/// Every semantic color token, in the order the stylesheet declares them.
///
/// The colors themselves are reached through the asset-catalog symbols Xcode
/// generates — `Color(.bgPage)` — so this list exists for one purpose: the debug
/// token gallery, which renders all of them and is how the port gets reviewed
/// without diffing hex codes by eye.
enum ColorTokens {
    struct Token: Identifiable {
        let name: String
        /// The custom property this came from, e.g. `--bg-page`.
        let css: String
        let color: Color

        var id: String { name }

        init(_ name: String, css: String, color: Color) {
            self.name = name
            self.css = css
            self.color = color
        }
    }

    static let all: [Token] = [
        Token("accent", css: "--accent", color: Color(.accent)),
        Token("accentContrast", css: "--accent-contrast", color: Color(.accentContrast)),
        Token("accentHover", css: "--accent-hover", color: Color(.accentHover)),
        Token("accentInk", css: "--accent-ink", color: Color(.accentInk)),
        Token("accentRing", css: "--accent-ring", color: Color(.accentRing)),
        Token("accentTint", css: "--accent-tint", color: Color(.accentTint)),
        Token("bgPage", css: "--bg-page", color: Color(.bgPage)),
        Token("bgSubtle", css: "--bg-subtle", color: Color(.bgSubtle)),
        Token("borderHairline", css: "--border-hairline", color: Color(.borderHairline)),
        Token("borderStrong", css: "--border-strong", color: Color(.borderStrong)),
        Token("chartDim", css: "--chart-dim", color: Color(.chartDim)),
        Token("chartGrid", css: "--chart-grid", color: Color(.chartGrid)),
        Token("chartLine", css: "--chart-line", color: Color(.chartLine)),
        Token("chartLineB", css: "--chart-line-b", color: Color(.chartLineB)),
        Token("chartLineC", css: "--chart-line-c", color: Color(.chartLineC)),
        Token("danger", css: "--danger", color: Color(.danger)),
        Token("dangerInk", css: "--danger-ink", color: Color(.dangerInk)),
        Token("dangerTint", css: "--danger-tint", color: Color(.dangerTint)),
        Token("mapFast", css: "--map-fast", color: Color(.mapFast)),
        Token("mapSlow", css: "--map-slow", color: Color(.mapSlow)),
        Token("mapTarmac", css: "--map-tarmac", color: Color(.mapTarmac)),
        Token("positive", css: "--positive", color: Color(.positive)),
        Token("shadow", css: "--shadow-color", color: Color(.shadow)),
        Token("surfaceCard", css: "--surface-card", color: Color(.surfaceCard)),
        Token("surfaceHover", css: "--surface-hover", color: Color(.surfaceHover)),
        Token("surfaceInput", css: "--surface-input", color: Color(.surfaceInput)),
        Token("surfaceRaised", css: "--surface-raised", color: Color(.surfaceRaised)),
        Token("textBody", css: "--text-body", color: Color(.textBody)),
        Token("textFaint", css: "--text-faint", color: Color(.textFaint)),
        Token("textMuted", css: "--text-muted", color: Color(.textMuted)),
        Token("textStrong", css: "--text-strong", color: Color(.textStrong)),
    ]
}
