// Generated by apps/ios/Tools/generate-tokens.mjs from public/style.css.
// Do not edit — change the stylesheet's tokens and re-run the generator.

import CoreGraphics

/// Layout dimensions shared with the web app.
///
/// The colours have been generated since NS-06; this is the first *layout*
/// token, added by NS-34 so that the width the app caps its content at is the
/// same number the web caps its page at, rather than a copy that drifts.
enum LayoutTokens {
    /// `--page-max`: how wide the content column is ever allowed to get.
    ///
    /// The phone layout never reaches it — it bites on a full-window iPad and on
    /// a tablet in landscape, which is exactly where an uncapped column reads as
    /// a stretched phone.
    static let PAGE_MAX: CGFloat = 1120

    /// `--page-gutter`: the web's page padding, used at medium width and above.
    ///
    /// `TESpacing.pageGutter` stays tighter than this on a phone, where 28pt of
    /// margin on each side is most of a column.
    static let PAGE_GUTTER: CGFloat = 28
}
