// Generates seed/seed.sql from seed data.
// Uses seed/data.personal.mjs (gitignored) if present, else seed/data.example.mjs.
// Run: node seed/generate.mjs
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const dir = dirname(fileURLToPath(import.meta.url));
const dataFile = existsSync(join(dir, "data.personal.mjs")) ? "./data.personal.mjs" : "./data.example.mjs";
const {
  USER_EMAIL, USER_NAME, TRACKS, EVENTS, RAW_EVENT_DATE, RAW_SESSIONS,
  // Garage logbook exports — optional so older data files still generate.
  VEHICLES = [], SETUPS = [], DEFAULT_CAR = null,
} = await import(dataFile);

// "2:01.24" | "1:58.6" | "3:06.520" -> milliseconds
function ms(t) {
  const m = /^(\d+):(\d{1,2})(?:\.(\d{1,3}))?$/.exec(t.trim());
  if (!m) throw new Error(`Bad time: ${t}`);
  const frac = m[3] ? Number(m[3].padEnd(3, "0")) : 0;
  return (Number(m[1]) * 60 + Number(m[2])) * 1000 + frac;
}

const q = (s) => (s == null ? "NULL" : `'${String(s).replace(/'/g, "''")}'`);

const lines = [
  `-- Generated by seed/generate.mjs from ${dataFile} — do not edit by hand.`,
  `INSERT INTO users (id, email, name) VALUES (1, ${q(USER_EMAIL)}, ${q(USER_NAME)});`,
];

const trackId = new Map(TRACKS.map((name, i) => [name, i + 1]));
for (const [name, id] of trackId) {
  // Seeding runs after migrations, so link to the canonical catalog inline
  // (the migration's backfill has already run by then).
  lines.push(
    `INSERT INTO tracks (id, user_id, name, catalog_id) VALUES (${id}, 1, ${q(name)}, ` +
      `(SELECT c.id FROM track_catalog c WHERE c.name = ${q(name)} COLLATE NOCASE));`
  );
}

// The garage: vehicles, their consumable parts, and wear measurements.
// Part keys are only a data-file convenience for referencing parts from
// setup sheets — they become plain ids here.
const vehicleId = new Map();
const partIdByKey = new Map();
let partId = 0;
VEHICLES.forEach((v, i) => {
  const vid = i + 1;
  vehicleId.set(v.name, vid);
  lines.push(
    `INSERT INTO vehicles (id, user_id, name, notes, is_default) VALUES (${vid}, 1, ${q(v.name)}, ${q(v.notes ?? null)}, ${v.default ? 1 : 0});`
  );
  for (const p of v.parts ?? []) {
    partId++;
    if (p.key) partIdByKey.set(p.key, partId);
    lines.push(
      `INSERT INTO parts (id, vehicle_id, kind, name, installed_on, retired_on, cost_cents, expected_hours, wear_limit, notes) ` +
        `VALUES (${partId}, ${vid}, ${q(p.kind)}, ${q(p.name)}, ${q(p.installed)}, ${q(p.retired ?? null)}, ` +
        `${p.cost != null ? Math.round(p.cost * 100) : "NULL"}, ${p.expected_hours ?? "NULL"}, ${p.wear_limit ?? "NULL"}, ${q(p.notes ?? null)});`
    );
    for (const [date, value, unit] of p.measurements ?? []) {
      lines.push(
        `INSERT INTO part_measurements (part_id, measured_on, value, unit) VALUES (${partId}, ${q(date)}, ${value}, ${q(unit ?? "mm")});`
      );
    }
  }
});

let sessionId = 0;
EVENTS.forEach(([date, days, club, group, track, best, notes, sessionBests, car], i) => {
  const eid = i + 1;
  const tid = trackId.get(track);
  if (!tid) throw new Error(`Unknown track: ${track}`);
  const carName = car ?? DEFAULT_CAR;
  const vid = carName != null && vehicleId.has(carName) ? vehicleId.get(carName) : null;
  lines.push(
    `INSERT INTO events (id, user_id, track_id, start_date, days, club, run_group, car, vehicle_id, notes, best_time_ms) ` +
      `VALUES (${eid}, 1, ${tid}, ${q(date)}, ${days}, ${q(club)}, ${q(group)}, ${q(carName)}, ${vid ?? "NULL"}, ${q(notes)}, ${best ? ms(best) : "NULL"});`
  );
  // The spreadsheet only recorded each session's best -> one-lap sessions.
  sessionBests.forEach((t, si) => {
    sessionId++;
    lines.push(
      `INSERT INTO sessions (id, event_id, label, sort) VALUES (${sessionId}, ${eid}, 'Session ${si + 1}', ${si + 1});`
    );
    lines.push(
      `INSERT INTO laps (session_id, lap_num, time_ms) VALUES (${sessionId}, 1, ${ms(t)});`
    );
  });
  if (RAW_EVENT_DATE && date === RAW_EVENT_DATE) {
    RAW_SESSIONS.forEach(([label, laps], si) => {
      sessionId++;
      lines.push(
        `INSERT INTO sessions (id, event_id, label, sort) VALUES (${sessionId}, ${eid}, ${q(label)}, ${si + 1});`
      );
      laps.forEach((t, li) => {
        lines.push(
          `INSERT INTO laps (session_id, lap_num, time_ms) VALUES (${sessionId}, ${li + 1}, ${ms(t)});`
        );
      });
    });
  }
});

// Per-event-day setup sheets; part refs resolve through the part keys above.
const eventIdByDate = new Map(EVENTS.map((e, i) => [e[0], i + 1]));
for (const s of SETUPS) {
  const eid = eventIdByDate.get(s.event);
  if (!eid) throw new Error(`Setup references unknown event date: ${s.event}`);
  const { parts, ...data } = s.data;
  for (const [from, to] of [["tires", "tires_id"], ["pads_f", "pads_f_id"], ["pads_r", "pads_r_id"]]) {
    if (!parts?.[from]) continue;
    const pid = partIdByKey.get(parts[from]);
    if (!pid) throw new Error(`Setup references unknown part key: ${parts[from]}`);
    data[to] = pid;
  }
  lines.push(`INSERT INTO setups (event_id, day, data) VALUES (${eid}, ${s.day}, ${q(JSON.stringify(data))});`);
}

const out = join(dir, "seed.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(
  `Wrote ${out} from ${dataFile}: ${EVENTS.length} events, ${sessionId} sessions, ${VEHICLES.length} vehicles, ${partId} parts, ${SETUPS.length} setups.`
);
