// Generated by apps/android/tools/generate-tokens.mjs from public/style.css.
// Do not edit — change the stylesheet's tokens and re-run the generator.

package app.trackevolution.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * Every semantic color token in the Track Evolution design system, ported from
 * `public/style.css`.
 *
 * The palette is semantic rather than Material: `surfaceCard`, `textMuted`,
 * `accentInk`, `chartLineB`, `mapSlow` have no counterpart in Material's
 * primary/secondary/tertiary roles, which is why this exists instead of leaning
 * on `ColorScheme`. Reach for it through `TrackTheme.colors`.
 */
@Immutable
data class TrackColors(
    val accent: Color,
    val accentContrast: Color,
    val accentHover: Color,
    val accentInk: Color,
    val accentRing: Color,
    val accentTint: Color,
    val bgPage: Color,
    val bgSubtle: Color,
    val borderHairline: Color,
    val borderStrong: Color,
    val chartDim: Color,
    val chartGrid: Color,
    val chartLine: Color,
    val chartLineB: Color,
    val chartLineC: Color,
    val danger: Color,
    val dangerInk: Color,
    val dangerTint: Color,
    val mapFast: Color,
    val mapSlow: Color,
    val mapTarmac: Color,
    val positive: Color,
    val shadow: Color,
    val surfaceCard: Color,
    val surfaceHover: Color,
    val surfaceInput: Color,
    val surfaceRaised: Color,
    val textBody: Color,
    val textFaint: Color,
    val textMuted: Color,
    val textStrong: Color,
)

/** The stylesheet's `:root, [data-theme="dark"]` block — the app's default. */
val DarkTrackColors: TrackColors = TrackColors(
    accent = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 1.000f),
    accentContrast = Color(red = 0.047f, green = 0.078f, blue = 0.000f, alpha = 1.000f),
    accentHover = Color(red = 0.835f, green = 0.984f, blue = 0.388f, alpha = 1.000f),
    accentInk = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 1.000f),
    accentRing = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 0.550f),
    accentTint = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 0.140f),
    bgPage = Color(red = 0.039f, green = 0.039f, blue = 0.043f, alpha = 1.000f),
    bgSubtle = Color(red = 0.055f, green = 0.055f, blue = 0.063f, alpha = 1.000f),
    borderHairline = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 0.090f),
    borderStrong = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 0.160f),
    chartDim = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 0.160f),
    chartGrid = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 0.070f),
    chartLine = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 1.000f),
    chartLineB = Color(red = 0.431f, green = 0.659f, blue = 1.000f, alpha = 1.000f),
    chartLineC = Color(red = 0.957f, green = 0.604f, blue = 0.753f, alpha = 1.000f),
    danger = Color(red = 0.949f, green = 0.447f, blue = 0.420f, alpha = 1.000f),
    dangerInk = Color(red = 0.949f, green = 0.447f, blue = 0.420f, alpha = 1.000f),
    dangerTint = Color(red = 0.949f, green = 0.447f, blue = 0.420f, alpha = 0.140f),
    mapFast = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 1.000f),
    mapSlow = Color(red = 0.227f, green = 0.259f, blue = 0.122f, alpha = 1.000f),
    mapTarmac = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 0.090f),
    positive = Color(red = 0.784f, green = 0.949f, blue = 0.306f, alpha = 1.000f),
    shadow = Color(red = 0.000f, green = 0.000f, blue = 0.000f, alpha = 0.550f),
    surfaceCard = Color(red = 0.075f, green = 0.075f, blue = 0.086f, alpha = 1.000f),
    surfaceHover = Color(red = 0.118f, green = 0.118f, blue = 0.137f, alpha = 1.000f),
    surfaceInput = Color(red = 0.078f, green = 0.078f, blue = 0.090f, alpha = 1.000f),
    surfaceRaised = Color(red = 0.102f, green = 0.102f, blue = 0.118f, alpha = 1.000f),
    textBody = Color(red = 0.839f, green = 0.839f, blue = 0.851f, alpha = 1.000f),
    textFaint = Color(red = 0.424f, green = 0.424f, blue = 0.451f, alpha = 1.000f),
    textMuted = Color(red = 0.592f, green = 0.592f, blue = 0.620f, alpha = 1.000f),
    textStrong = Color(red = 0.965f, green = 0.965f, blue = 0.969f, alpha = 1.000f),
)

/**
 * The stylesheet's `[data-theme="light"]` block.
 *
 * Not a lightness flip of the dark scheme: `accentInk` is `#c8f24e` dark and
 * `#4c6a00` light, and the chart series change hue entirely. Deriving one from
 * the other would make light mode unreadable.
 */
val LightTrackColors: TrackColors = TrackColors(
    accent = Color(red = 0.714f, green = 0.894f, blue = 0.173f, alpha = 1.000f),
    accentContrast = Color(red = 0.047f, green = 0.078f, blue = 0.000f, alpha = 1.000f),
    accentHover = Color(red = 0.655f, green = 0.835f, blue = 0.125f, alpha = 1.000f),
    accentInk = Color(red = 0.298f, green = 0.416f, blue = 0.000f, alpha = 1.000f),
    accentRing = Color(red = 0.471f, green = 0.659f, blue = 0.000f, alpha = 0.450f),
    accentTint = Color(red = 0.471f, green = 0.659f, blue = 0.000f, alpha = 0.140f),
    bgPage = Color(red = 0.984f, green = 0.984f, blue = 0.980f, alpha = 1.000f),
    bgSubtle = Color(red = 0.957f, green = 0.957f, blue = 0.949f, alpha = 1.000f),
    borderHairline = Color(red = 0.000f, green = 0.000f, blue = 0.000f, alpha = 0.100f),
    borderStrong = Color(red = 0.000f, green = 0.000f, blue = 0.000f, alpha = 0.180f),
    chartDim = Color(red = 0.000f, green = 0.000f, blue = 0.000f, alpha = 0.150f),
    chartGrid = Color(red = 0.000f, green = 0.000f, blue = 0.000f, alpha = 0.080f),
    chartLine = Color(red = 0.435f, green = 0.612f, blue = 0.000f, alpha = 1.000f),
    chartLineB = Color(red = 0.184f, green = 0.435f, blue = 0.839f, alpha = 1.000f),
    chartLineC = Color(red = 0.690f, green = 0.204f, blue = 0.561f, alpha = 1.000f),
    danger = Color(red = 0.839f, green = 0.290f, blue = 0.263f, alpha = 1.000f),
    dangerInk = Color(red = 0.761f, green = 0.227f, blue = 0.200f, alpha = 1.000f),
    dangerTint = Color(red = 0.839f, green = 0.290f, blue = 0.263f, alpha = 0.100f),
    mapFast = Color(red = 0.298f, green = 0.416f, blue = 0.000f, alpha = 1.000f),
    mapSlow = Color(red = 0.863f, green = 0.910f, blue = 0.706f, alpha = 1.000f),
    mapTarmac = Color(red = 0.000f, green = 0.000f, blue = 0.000f, alpha = 0.100f),
    positive = Color(red = 0.298f, green = 0.416f, blue = 0.000f, alpha = 1.000f),
    shadow = Color(red = 0.078f, green = 0.086f, blue = 0.059f, alpha = 0.140f),
    surfaceCard = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 1.000f),
    surfaceHover = Color(red = 0.937f, green = 0.937f, blue = 0.925f, alpha = 1.000f),
    surfaceInput = Color(red = 1.000f, green = 1.000f, blue = 1.000f, alpha = 1.000f),
    surfaceRaised = Color(red = 0.965f, green = 0.965f, blue = 0.957f, alpha = 1.000f),
    textBody = Color(red = 0.173f, green = 0.173f, blue = 0.188f, alpha = 1.000f),
    textFaint = Color(red = 0.588f, green = 0.588f, blue = 0.616f, alpha = 1.000f),
    textMuted = Color(red = 0.388f, green = 0.388f, blue = 0.416f, alpha = 1.000f),
    textStrong = Color(red = 0.063f, green = 0.063f, blue = 0.071f, alpha = 1.000f),
)

/** One token, for the debug token gallery. */
@Immutable
data class ColorToken(
    val name: String,
    /** The custom property this came from, e.g. `--bg-page`. */
    val css: String,
    val select: (TrackColors) -> Color,
)

/** Every token, in stylesheet-name order. Drives the gallery. */
val ColorTokenCatalog: List<ColorToken> = listOf(
    ColorToken("accent", "--accent", TrackColors::accent),
    ColorToken("accentContrast", "--accent-contrast", TrackColors::accentContrast),
    ColorToken("accentHover", "--accent-hover", TrackColors::accentHover),
    ColorToken("accentInk", "--accent-ink", TrackColors::accentInk),
    ColorToken("accentRing", "--accent-ring", TrackColors::accentRing),
    ColorToken("accentTint", "--accent-tint", TrackColors::accentTint),
    ColorToken("bgPage", "--bg-page", TrackColors::bgPage),
    ColorToken("bgSubtle", "--bg-subtle", TrackColors::bgSubtle),
    ColorToken("borderHairline", "--border-hairline", TrackColors::borderHairline),
    ColorToken("borderStrong", "--border-strong", TrackColors::borderStrong),
    ColorToken("chartDim", "--chart-dim", TrackColors::chartDim),
    ColorToken("chartGrid", "--chart-grid", TrackColors::chartGrid),
    ColorToken("chartLine", "--chart-line", TrackColors::chartLine),
    ColorToken("chartLineB", "--chart-line-b", TrackColors::chartLineB),
    ColorToken("chartLineC", "--chart-line-c", TrackColors::chartLineC),
    ColorToken("danger", "--danger", TrackColors::danger),
    ColorToken("dangerInk", "--danger-ink", TrackColors::dangerInk),
    ColorToken("dangerTint", "--danger-tint", TrackColors::dangerTint),
    ColorToken("mapFast", "--map-fast", TrackColors::mapFast),
    ColorToken("mapSlow", "--map-slow", TrackColors::mapSlow),
    ColorToken("mapTarmac", "--map-tarmac", TrackColors::mapTarmac),
    ColorToken("positive", "--positive", TrackColors::positive),
    ColorToken("shadow", "--shadow-color", TrackColors::shadow),
    ColorToken("surfaceCard", "--surface-card", TrackColors::surfaceCard),
    ColorToken("surfaceHover", "--surface-hover", TrackColors::surfaceHover),
    ColorToken("surfaceInput", "--surface-input", TrackColors::surfaceInput),
    ColorToken("surfaceRaised", "--surface-raised", TrackColors::surfaceRaised),
    ColorToken("textBody", "--text-body", TrackColors::textBody),
    ColorToken("textFaint", "--text-faint", TrackColors::textFaint),
    ColorToken("textMuted", "--text-muted", TrackColors::textMuted),
    ColorToken("textStrong", "--text-strong", TrackColors::textStrong),
)
