// Generated by apps/android/tools/generate-tokens.mjs from public/style.css.
// Do not edit — change the stylesheet's tokens and re-run the generator.

package app.trackevolution.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Layout dimensions shared with the web app.
 *
 * The colours have been generated since NS-07; this is the first *layout* token,
 * added by NS-34 so that the width the app caps its content at is the same
 * number the web caps its page at, rather than a copy that drifts. The iOS
 * counterpart is `LayoutTokens.swift`, generated from the same declarations.
 *
 * In `dp`, not `sp`: a page width is a physical dimension. A column that grew
 * with the font-size setting would get *wider* exactly when the text needs it
 * narrower.
 */
object LayoutTokens {
    /** `--page-max`: how wide the content column is ever allowed to get. */
    val PAGE_MAX: Dp = 1120.dp

    /** `--page-gutter`: the web's page padding, used at medium width and above. */
    val PAGE_GUTTER: Dp = 28.dp
}
