package app.trackevolution.core

import app.trackevolution.core.model.Lap
import app.trackevolution.core.model.LapChannels
import app.trackevolution.core.model.SessionChannels
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * The port of `test/unit/channel-graphs.test.js`, plus the cross-language pin.
 */
class ChannelGraphsTest {

    private fun lap(num: Int, ms: Int) = Lap(id = num, sessionId = 1, lapNum = num, timeMs = ms)

    private fun channels(vararg laps: LapChannels, step: Double = 20.0) =
        SessionChannels(v = 1, dStepM = step, laps = laps.toList())

    // ---- the cross-language contract ---------------------------------------

    @Test
    fun `matches the web implementation's reference output`() {
        // contracts/logic/channels.json is generated by running the *web*
        // implementation, so this asserts equality with the reference rather
        // than with the Swift port — the two could agree and both be wrong.
        val fixture = Json.parseToJsonElement(
            RepoRoot.path("contracts/logic/channels.json").readText(),
        ).jsonObject

        val input = fixture["input"]!!.jsonObject
        val sessionLaps = input["sessionLaps"]!!.jsonArray.map {
            val o = it.jsonObject
            lap(o["lap_num"]!!.jsonPrimitive.content.toInt(), o["time_ms"]!!.jsonPrimitive.content.toInt())
        }
        val chLaps = input["channelLaps"]!!.jsonArray.map {
            val o = it.jsonObject
            LapChannels(
                n = o["n"]!!.jsonPrimitive.content.toInt(),
                timeMs = o["timeMs"]!!.jsonPrimitive.content.toInt(),
            )
        }
        val expected = (fixture["expected"] as JsonObject)["chIdx"]!!.jsonArray
            .map { it.jsonPrimitive.content.toInt() }

        assertEquals(expected, ChannelGraphs.matchLapsToChannels(sessionLaps, chLaps).map { it.chIdx })
    }

    // ---- matching ----------------------------------------------------------

    @Test
    fun `never reuses a channel entry for two laps sharing a time`() {
        // The reason the match walks forward and never rewinds.
        val matches = ChannelGraphs.matchLapsToChannels(
            listOf(lap(1, 120_400), lap(2, 120_400)),
            listOf(LapChannels(n = 1, timeMs = 120_400), LapChannels(n = 2, timeMs = 120_400)),
        )
        assertEquals(listOf(0, 1), matches.map { it.chIdx })
    }

    @Test
    fun `marks a lap with no channel data with the -1 sentinel`() {
        val matches = ChannelGraphs.matchLapsToChannels(
            listOf(lap(1, 121_900), lap(2, 119_800)),
            listOf(LapChannels(n = 1, timeMs = 121_900)),
        )
        assertEquals(listOf(0, -1), matches.map { it.chIdx })
        assertTrue(matches[0].hasChannels)
        assertTrue(!matches[1].hasChannels)
    }

    // ---- selection ---------------------------------------------------------

    @Test
    fun `pre-selects the fastest lap that actually has channels`() {
        // The session's best lap has no channel data, so opening on it would
        // show an empty chart.
        val matches = ChannelGraphs.matchLapsToChannels(
            listOf(lap(1, 121_900), lap(2, 120_400), lap(3, 118_000)),
            listOf(LapChannels(n = 1, timeMs = 121_900), LapChannels(n = 2, timeMs = 120_400)),
        )
        assertEquals(listOf(1), ChannelGraphs.initialSelection(matches))
    }

    @Test
    fun `selects nothing when no lap has channels`() {
        val matches = ChannelGraphs.matchLapsToChannels(listOf(lap(1, 121_900)), emptyList())
        assertTrue(ChannelGraphs.initialSelection(matches).isEmpty())
    }

    @Test
    fun `toggles a lap out again`() {
        assertEquals(listOf(0, 2), ChannelGraphs.toggle(1, listOf(0, 1, 2)))
    }

    @Test
    fun `evicts the oldest selection past three slots`() {
        assertEquals(listOf(1, 2, 3), ChannelGraphs.toggle(3, listOf(0, 1, 2)))
    }

    // ---- axes --------------------------------------------------------------

    @Test
    fun `spans the longest lap on a shared distance axis`() {
        val ch = channels(
            LapChannels(n = 1, timeMs = 1, speed = listOf(1.0, 2.0, 3.0)),
            LapChannels(n = 2, timeMs = 2, speed = listOf(1.0, 2.0, 3.0, 4.0, 5.0)),
        )
        assertEquals(5, ChannelGraphs.gridCount(ChannelGraphs.Channel.SPEED, ch))
        assertEquals(80.0, ChannelGraphs.distanceSpan(ChannelGraphs.Channel.SPEED, ch))
    }

    @Test
    fun `converts stored kph to mph for the speed axis`() {
        val ch = channels(LapChannels(n = 1, timeMs = 1, speed = listOf(100.0)))
        val domain = ChannelGraphs.valueDomain(ChannelGraphs.Channel.SPEED, ch)!!
        // 100 kph is 62.1371 mph, and a single value gets the 1e-6 pad floor.
        assertTrue(domain.low < 62.1372 && domain.high > 62.137)
    }

    @Test
    fun `pins lateral G's axis to zero so left and right compare`() {
        val ch = channels(LapChannels(n = 1, timeMs = 1, latG = listOf(0.4, 1.2)))
        val domain = ChannelGraphs.valueDomain(ChannelGraphs.Channel.LAT_G, ch)!!
        assertEquals(0.0, domain.low)
        assertTrue(domain.high > 1.2, "the top is still padded")
    }

    @Test
    fun `pads both ends for a channel that does not floor at zero`() {
        val ch = channels(LapChannels(n = 1, timeMs = 1, rpm = listOf(2000.0, 7000.0)))
        val domain = ChannelGraphs.valueDomain(ChannelGraphs.Channel.RPM, ch)!!
        assertEquals(1600.0, domain.low)
        assertEquals(7400.0, domain.high)
    }

    @Test
    fun `reports no domain for a channel nothing carries`() {
        val ch = channels(LapChannels(n = 1, timeMs = 1, speed = listOf(1.0)))
        assertNull(ChannelGraphs.valueDomain(ChannelGraphs.Channel.RPM, ch))
    }

    @Test
    fun `lists only the channels some lap carries`() {
        val ch = channels(
            LapChannels(n = 1, timeMs = 1, speed = listOf(1.0)),
            LapChannels(n = 2, timeMs = 2, speed = listOf(1.0), latG = listOf(0.1)),
        )
        assertEquals(
            listOf(ChannelGraphs.Channel.SPEED, ChannelGraphs.Channel.LAT_G),
            ChannelGraphs.presentChannels(ch),
        )
    }

    // ---- read-out ----------------------------------------------------------

    @Test
    fun `finds the grid index nearest a distance and clamps to the series`() {
        val ch = channels(LapChannels(n = 1, timeMs = 1, speed = listOf(1.0, 2.0, 3.0)))
        assertEquals(2, ChannelGraphs.gridIndex(41.0, ChannelGraphs.Channel.SPEED, ch))
        assertEquals(0, ChannelGraphs.gridIndex(-5.0, ChannelGraphs.Channel.SPEED, ch))
        assertEquals(2, ChannelGraphs.gridIndex(9999.0, ChannelGraphs.Channel.SPEED, ch))
    }

    @Test
    fun `reads a converted value, or null past the end of a short lap`() {
        val ch = channels(
            LapChannels(n = 1, timeMs = 1, speed = listOf(100.0, 110.0)),
            LapChannels(n = 2, timeMs = 2, speed = listOf(100.0)),
        )
        assertEquals(62.1371, ChannelGraphs.value(ChannelGraphs.Channel.SPEED, 0, 0, ch)!!, 1e-9)
        assertNull(ChannelGraphs.value(ChannelGraphs.Channel.SPEED, 1, 1, ch))
    }

    @Test
    fun `formats distances the way the axis labels do`() {
        assertEquals("800 m", ChannelGraphs.fmtDist(800.0))
        assertEquals("2 km", ChannelGraphs.fmtDist(2000.0))
        assertEquals("1.5 km", ChannelGraphs.fmtDist(1500.0))
    }
}
