package app.trackevolution.core

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.sin
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * The port of `test/unit/live-timing.test.js`, plus the cross-language pin.
 */
class LiveTimingTest {

    private val lat0 = 36.56
    private val lon0 = -79.2
    private val kx = 111320.0 * cos(lat0 * PI / 180.0)
    private val ky = 110540.0
    private val r = 200.0

    /** Same synthetic circle as the JS unit tests: 5 Hz, one speed per lap. */
    private fun circleFixes(lapSpeeds: List<Double>, hz: Int = 5): List<Fix> {
        val fixes = ArrayList<Fix>()
        var t = 0.0
        var a = 0.0
        val dt = 1.0 / hz
        for (v in lapSpeeds) {
            val lapS = 2 * PI * r / v
            val n = java.lang.Math.round(lapS * hz).toInt()
            repeat(n) {
                fixes.add(
                    Fix(
                        t = JsMath.round(t, 100.0),
                        lat = lat0 + r * sin(a) / ky,
                        lon = lon0 + r * cos(a) / kx,
                        speed = v,
                        accuracy = 5.0,
                    ),
                )
                t += dt
                a += v * dt / r
            }
        }
        return fixes
    }

    private val lap25Ms = JsMath.roundToInt(2 * PI * r / 25.0 * 1000)

    // ---- the cross-language contract ---------------------------------------

    @Test
    fun `matches the web implementation's reference output`() {
        // contracts/logic/live-timing.json is generated by running the *web*
        // implementation — assert against the reference, never the iOS port.
        val fixture = Json.parseToJsonElement(
            RepoRoot.path("contracts/logic/live-timing.json").readText(),
        ).jsonObject
        val fixes = fixture["input"]!!.jsonObject["fixes"]!!.jsonArray.map {
            val f = it.jsonArray
            Fix(
                t = f[0].jsonPrimitive.content.toDouble(),
                lat = f[1].jsonPrimitive.content.toDouble(),
                lon = f[2].jsonPrimitive.content.toDouble(),
                speed = if (f[3] is JsonNull) null else f[3].jsonPrimitive.content.toDouble(),
                accuracy = if (f[4] is JsonNull) null else f[4].jsonPrimitive.content.toDouble(),
            )
        }
        val expected = fixture["expected"]!!.jsonObject

        val lt = LiveTiming()
        val deltas = expected["deltaAfterEachFix"]!!.jsonArray
        assertEquals(fixes.size, deltas.size)
        fixes.forEachIndexed { i, f ->
            lt.addTimingFix(f)
            val want = deltas[i]
            if (want is JsonNull) {
                assertNull(lt.deltaS, "fix $i: expected no delta")
            } else {
                val w = want.jsonPrimitive.content.toDouble()
                assertNotNull(lt.deltaS, "fix $i: expected a delta")
                assertTrue(abs(lt.deltaS!! - w) < 1e-9, "fix $i: delta ${lt.deltaS} != $w")
            }
        }

        assertEquals(expected["lapCount"]!!.jsonPrimitive.content.toInt(), lt.lapCount)
        assertEquals(expected["lastLapMs"]!!.jsonPrimitive.content.toInt(), lt.lastLapMs)
        assertEquals(expected["bestLapMs"]!!.jsonPrimitive.content.toInt(), lt.bestLapMs)

        val gate = expected["gate"]!!.jsonObject
        val got = lt.gate!!
        for ((key, value) in mapOf(
            "hx" to got.hx, "hy" to got.hy,
            "x1" to got.x1, "y1" to got.y1,
            "x2" to got.x2, "y2" to got.y2,
        )) {
            assertTrue(
                abs(gate[key]!!.jsonPrimitive.content.toDouble() - value) < 1e-9,
                "gate.$key: $value",
            )
        }

        val display = expected["finalDisplay"]!!.jsonObject
        val gotDisplay = lt.liveTimingDisplay(fixes.last().t)
        assertEquals(display["lapCount"]!!.jsonPrimitive.content.toInt(), gotDisplay.lapCount)
        assertTrue(
            abs(display["currentLapS"]!!.jsonPrimitive.content.toDouble() - gotDisplay.currentLapS!!) < 1e-9,
        )
    }

    // ---- ported JS unit tests -----------------------------------------------

    @Test
    fun `stays disarmed below track pace`() {
        val lt = LiveTiming()
        for (f in circleFixes(listOf(5.0)).take(100)) lt.addTimingFix(f)
        assertNull(lt.gate)
        assertNull(lt.liveTimingDisplay(20.0).currentLapS)
    }

    @Test
    fun `arms at track pace and times laps at the circle period`() {
        val lt = LiveTiming.liveTimingFromFixes(circleFixes(listOf(25.0, 25.0, 25.0, 25.0)))
        assertNotNull(lt.gate)
        assertEquals(3, lt.lapCount)
        assertTrue(abs(lt.lastLapMs!! - lap25Ms) < 150)
        assertTrue(abs(lt.bestLapMs!! - lap25Ms) < 150)
    }

    @Test
    fun `shows a growing positive delta on a slower lap`() {
        val lt = LiveTiming.liveTimingFromFixes(circleFixes(listOf(25.0, 25.0, 20.0)))
        assertTrue(lt.deltaS!! > 8.0)
    }

    @Test
    fun `promotes a faster lap to the reference`() {
        val lt = LiveTiming.liveTimingFromFixes(circleFixes(listOf(25.0, 30.0, 30.0)))
        val lap30 = JsMath.roundToInt(2 * PI * r / 30.0 * 1000)
        assertTrue(abs(lt.bestLapMs!! - lap30) < 150)
        assertTrue(lt.bestLapMs!! < lap25Ms)
    }

    @Test
    fun `negative delta when running ahead of the best lap`() {
        val fixes = circleFixes(listOf(25.0, 30.0))
        val lt = LiveTiming()
        for (f in fixes.take((fixes.size * 0.85).toInt())) lt.addTimingFix(f)
        assertEquals(1, lt.lapCount)
        assertTrue(lt.deltaS!! < -1.0)
    }

    @Test
    fun `arming needs a real heading, not a GPS teleport at zero speed`() {
        val lt = LiveTiming()
        lt.addTimingFix(Fix(t = 0.0, lat = lat0, lon = lon0, speed = LiveTiming.ARM_MPS + 1, accuracy = 5.0))
        lt.addTimingFix(Fix(t = 1.0, lat = lat0, lon = lon0 + 0.5 / kx, speed = LiveTiming.ARM_MPS + 1, accuracy = 5.0))
        assertNull(lt.gate)
    }
}
