package app.trackevolution.core

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

/**
 * Checkpoint (de)serialization — the format the recorder writes every ~10 s so
 * a recording survives the app being killed mid-session.
 *
 * Two properties matter and both are tested here:
 *
 *  1. **A corrupt checkpoint must never crash launch.** Anything implausible
 *     deserializes to null; nothing throws.
 *  2. **The format is shared with the web and iOS clients.** The fixture in
 *     `contracts/fixtures/recording-checkpoint.json` is generated by importing
 *     the real `public/js/record/core.js` (`npm run fixtures:generate`), so if
 *     this suite passes, a checkpoint written on the web reads here — and the
 *     re-serialization assertion proves the reverse direction byte for byte.
 */
class RecordingCheckpointTest {

    private fun webCheckpoint(): String =
        checkNotNull(javaClass.getResourceAsStream("/recording-checkpoint.json")) {
            "missing shared fixture — run `npm run fixtures:generate` at the repo root"
        }.use { it.readBytes().decodeToString() }

    @Test
    fun `round-trips a recording`() {
        val rec = createRecording(7L, 1_750_000_000_000.0)
        for (t in 0 until 20) {
            rec.addFix(GpsFix(1_750_000_000_000.0 + t * 1000, 36.56 + t / 110540.0, -79.2, t * 1.5, 4.0))
        }
        val snapshot = rec.snapshot()
        assertEquals(snapshot, deserializeRecording(serializeRecording(snapshot)))
    }

    @Test
    fun `round-trips a recording started without an event`() {
        // Android Auto starts recordings before the event exists; eventId is
        // null until the event's record screen adopts it.
        val rec = createRecording(null, 1_750_000_000_000.0)
        rec.addFix(GpsFix(1_750_000_000_000.0, 36.56, -79.2))
        val snapshot = rec.snapshot()
        val json = serializeRecording(snapshot)
        assertTrue(json.contains("\"eventId\":null")) { json }
        assertEquals(snapshot, deserializeRecording(json))
    }

    @ParameterizedTest(name = "rejects {0}")
    @ValueSource(
        strings = [
            "not json{",
            "",
            "[]",
            "null",
            """{"v":99,"fixes":[]}""",
            """{"v":"1","startedAtMs":0,"fixes":[]}""",
            """{"v":1.5,"startedAtMs":0,"fixes":[]}""",
            """{"v":1,"fixes":[]}""",
            """{"v":1,"startedAtMs":null,"fixes":[]}""",
            """{"v":1,"startedAtMs":0}""",
            """{"v":1,"startedAtMs":0,"fixes":{}}""",
            """{"v":1,"startedAtMs":0,"fixes":[["x"]]}""",
            """{"v":1,"startedAtMs":0,"fixes":[[1,2]]}""",
            """{"v":1,"startedAtMs":0,"fixes":[[1,2,"3"]]}""",
            """{"v":1,"startedAtMs":0,"fixes":[[null,2,3]]}""",
            """{"v":1,"startedAtMs":0,"fixes":[[1,2,3],[4,5""",
        ],
    )
    fun `rejects corrupt checkpoints instead of throwing`(json: String) {
        assertNull(deserializeRecording(json))
    }

    @Test
    fun `rejects a null checkpoint`() {
        assertNull(deserializeRecording(null))
    }

    @Test
    fun `accepts a three-element fix tuple`() {
        // Speed and accuracy are absent, not invalid — the watcher reports
        // neither on some devices.
        val rec = requireNotNull(deserializeRecording("""{"v":1,"startedAtMs":0,"fixes":[[1,36.5,-79.2]]}"""))
        assertEquals(Fix(1.0, 36.5, -79.2, null, null), rec.fixes[0])
    }

    @Test
    fun `reads a checkpoint written by the web client`() {
        val rec = requireNotNull(deserializeRecording(webCheckpoint()))
        assertEquals(RECORDING_V, rec.v)
        assertEquals(42L, rec.eventId)
        assertEquals(1_750_000_000_000.0, rec.startedAtMs)
        assertEquals(141, rec.fixes.size)
        assertEquals(Fix(0.0, 36.56, -79.205592, 0.0, 12.5), rec.fixes.first())
        // The trace survives into the review pipeline: 30 s of paddock idle
        // either side is trimmed to a margin, and the driving is intact.
        val parsed = requireNotNull(toParsed(rec))
        assertEquals("live", parsed.kind)
        assertTrue(parsed.durationS > 60) { "got ${parsed.durationS} s" }
    }

    @Test
    fun `writes a checkpoint the web client would write, byte for byte`() {
        // The strongest statement of cross-client compatibility available
        // without running three runtimes: parse the web's own output, write it
        // back, and require the exact same bytes — key order, tuple encoding
        // and number formatting included.
        val json = webCheckpoint()
        assertEquals(json, serializeRecording(requireNotNull(deserializeRecording(json))))
    }

    @Test
    fun `formats numbers the way JSON stringify does`() {
        // Java would write these as 1.0, 1.75E12 and 1.0E-4; JavaScript writes
        // 1, 1750000000000 and 0.0001. A checkpoint that parses the same but
        // compares differently makes cross-client bugs invisible.
        assertEquals("1", jsNumber(1.0))
        assertEquals("1750000000000", jsNumber(1.75e12))
        assertEquals("0.0001", jsNumber(1e-4))
        assertEquals("0.000001", jsNumber(1e-6))
        assertEquals("0", jsNumber(0.0))
        assertEquals("0", jsNumber(-0.0))
        assertEquals("36.56", jsNumber(36.56))
        assertEquals("-79.205592", jsNumber(-79.205592))
        assertEquals("0.01", jsNumber(0.01))
    }
}
