// Cross-client fixtures for the native ports.
//
// Unlike contracts/golden/ (captured API responses), these are artifacts the
// *web client* produces that the Swift (NS-11) and Kotlin (NS-12) ports must
// read byte-identically. They are generated by importing the real web modules,
// not hand-written, so a change to the format shows up here as a diff instead
// of as a silent cross-client incompatibility.
//
// Determinism is mandatory — regenerating without a source change must produce
// a byte-identical file, so nothing here may use Date.now() or randomness.
//
// Run with: npm run fixtures:generate   (npm run fixtures:check in CI)

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { addFix, createRecording, serializeRecording } from "../../public/js/record/core.js";

const OUT_DIR = path.dirname(fileURLToPath(import.meta.url));

// A short but realistic track-day recording at 1 Hz: idle in the paddock, a
// lap and a half of a 200 m-radius circle at 25 m/s, then idle again. Small
// enough to read in a diff, long enough that toParsed() returns a usable trace
// (30+ fixes and 60+ seconds survive the idle trim).
const LAT0 = 36.56;
const LON0 = -79.2;
const KX = 111320 * Math.cos((LAT0 * Math.PI) / 180);
const KY = 110540;
const STARTED_AT_MS = 1750000000000; // 2025-06-15T15:06:40Z — fixed, never Date.now()

function recordingCheckpoint() {
  const rec = createRecording(42, STARTED_AT_MS);
  const speed = 25;
  const radius = 200;
  let t = 0;
  const push = (lat, lon, v, accuracy) =>
    addFix(rec, { timeMs: STARTED_AT_MS + t++ * 1000, lat, lon, speed: v, accuracy });

  for (let i = 0; i < 30; i++) push(LAT0, LON0 - 500 / KX, 0, 12.5);
  for (let i = 0; i <= 80; i++) {
    const a = (i * speed) / radius;
    push(LAT0 + (radius * Math.sin(a)) / KY, LON0 + (radius * Math.cos(a)) / KX, speed, 4.8);
  }
  for (let i = 0; i < 30; i++) push(LAT0, LON0 - 500 / KX, 0, 12.5);
  return serializeRecording(rec);
}

mkdirSync(OUT_DIR, { recursive: true });
const target = path.join(OUT_DIR, "recording-checkpoint.json");
writeFileSync(target, recordingCheckpoint());
console.log(`wrote ${path.relative(process.cwd(), target)}`);
